version: "3.9"

services:
  service_users:
    build: ./service_users
    container_name: service_users
    environment:
      - APP_ENV=dev
      - JWT_SECRET=dev-secret-change-me
    ports:
      - "8081:8081"

  service_orders:
    build: ./service_orders
    container_name: service_orders
    environment:
      - APP_ENV=dev
      - JWT_SECRET=dev-secret-change-me
    ports:
      - "8082:8082"
    depends_on:
      - service_users

  api_gateway:
    build: ./api_gateway
    container_name: api_gateway
    environment:
      - APP_ENV=dev
      - JWT_SECRET=dev-secret-change-me
      - USERS_SERVICE_URL=http://service_users:8081
      - ORDERS_SERVICE_URL=http://service_orders:8082
    ports:
      - "8080:8080"
    depends_on:
      - service_users
      - service_orders
